### ISSUE TITLE
Extended Characters in URI Corrupted when DISK-QUEUE=true

### ISSUE THREAD

**Issue by mikerosiak** [marklogic-community/corb2#108]
When an extended character (e.g. Unicode hyphen 8208) is in a URI, and **DISK-QUEUE=true**, the character is translated to a literal '?' during the queue read/write process.  Subsequently, the call to `fn.doc()` for the URI in the transform module fails.  

Tested on a Windows machine.

**Comment by hansenmc** [comment]
It seems that the DiskQueue is relying on the OS character encoding when using the `FileWriter` and `FileReader`. On windows with `cp1252` multi-byte characters are getting mangled when the writer attempts to write characters.

https://github.com/marklogic-community/corb2/blob/master/src/main/java/com/marklogic/developer/corb/DiskQueue.java#L157

Instead, we should be using `FileOutputStreamWriter` and `FileInputStreamReader` with explicit encoding.

    fileOut = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(fileQueue), StandardCharsets.UTF_8));

    // Flush output file, so there's something written when we open the input stream.
    fileOut.flush();

    fileIn = new BufferedReader(new InputStreamReader(new FileInputStream(fileQueue), StandardCharsets.UTF_8));

I have developed on a Mac and the CI servers are Linux, so would never have noticed. I'll work on getting a test setup to reproduce the behavior and we can get a release out soon to fix this.

In the meantime, you could try explicitly setting the character encoding for the Java process that is invoking the CoRB job to UTF-8: 

    -Dfile.encoding=UTF-8
