### ISSUE TITLE
Error thrown when trying to test if password is URL encoded

### ISSUE THREAD

**Issue by bshalke** [marklogic-community/corb2#126]
CoRB tries to determine automatically if properties are URL encoded, but chokes on non-url encoded values with a % as the second-last character.

https://github.com/marklogic-community/corb2/blob/52b547b10ea39596cc08ec085fb2458fd5b99eb2/src/main/java/com/marklogic/developer/corb/util/StringUtils.java#L362

This throws an "java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern" error, which should be caught and return false, as the property isn't properly URL encoded.

It might be helpful if there was also a flag to override this automatic checking behavior and be set to either always or never url encode properties.

**Comment by hansenmc** [comment]
Thank you for the analysis. Indeed, the exception should be caught and return `false` if a value can't be decoded, which will help in most cases. 

And I also agree that it would be helpful to have an option that would allow people to disable the checks. What should the option be called?

- XCC-COMPNENT-ENCODE
- XCC-DETECT-URL-ENCODE

@bbandlamudi what are your thoughts?

**Comment by bshalke** [comment]
I would say the option should be something more self explanatory.

URL-ENCODE-PROPERTIES with possible values being Always, Never and Auto?

**Comment by bbandlamudi** [comment]
I also agree with more explicit name for the option, which is inline with other options. ex: URL-ENCODE-[CHECK, MODE, OPTION] etc . Multiple options (either string or numeric) sounds good, if it is useful.
