### ISSUE TITLE
Update SSL config to use TLSv1.2

### ISSUE THREAD

**Issue by jkerr5** [marklogic-community/corb2#140]
The default SSL config uses SSLv3 which is disabled on most machines now. It should be updated to use TLSv1.2.

**Comment by hansenmc** [comment]
Yes, will update that for the default and look to expose as a configurable value, for future

**Comment by jkerr5** [comment]
Thanks @hansenmc Any thoughts on getting a quick turnaround on this? I'm using my own custom SSL config class as a workaround right now but it would simplify for our customer if I didn't have to do that.

**Comment by hansenmc** [comment]
Yes, working on it now. Using this as an opportunity to do just a little bit more than have hard-coded default changed. Goin to have the TrustAnyoneSSLConfig read *SSL-ENABLED-PROTOCOLS* and doing a little cleanup.
