### ISSUE TITLE
Job server web page should update after the job completes

### ISSUE THREAD

**Issue by nickawatts** [marklogic-community/corb2#184]
The job page does not update one last time after a job completes. It would be helpful, especially since the job server automatically shuts down upon job completion, to see that the job completed, its exit code, final stats, etc... on the job page. This information does get logged but doesn't make it to the job's web page if the job web server is running. This feature would be helpful for when you're monitoring a job from the job server rather than watching the log.

**Comment by hansenmc** [comment]
I agree. The challenge is figuring out how long it should stay up before exiting. But maybe we can look at delaying shutdown by a few seconds in order for the metrics refresh to be able to make another final call.

Currently, it invokes 

    jobserver.stop(0)

https://github.com/marklogic-community/corb2/blob/a2a8017dffa845e84a68d9f59ed163aa9285aa7d/src/main/java/com/marklogic/developer/corb/Manager.java#L139

Maybe it needs to delay the shutdown by 2 times the metrics refresh interval (currently 5 seconds), to ensure that it has a chance to fetch the final stats before the server shuts itself down.

https://github.com/marklogic-community/corb2/blob/8de6714d5dcf6179bb223a43c8570f1bfaccb7bf/src/main/resources/web/js/corbApp.js#L117

**Comment by nickawatts** [comment]
I'm not sure if you need this, but I tried out the change and it worked for me. One thing I'd still like to see is the exit code listed somewhere on the GUI. Adding a noticeable indication for a non-zero exit status would be great too. I can put that in a different issue if necessary.
