### ISSUE TITLE
TLS certificate failing to connect (but the same cert works fine with MLCP)

### ISSUE THREAD

**Issue by mlzarathustra** [marklogic-community/corb2#202]
This exact same cert and password work just fine for both MLCP and a custom java app I wrote (xq-java) but it fails with "handshake_failure" when I try with CORB.

Here is the command line (with passwords &c. redacted) including a debug flag that generates a ton of output. Without that flag, CORB doesn't report the actual problem (the handshake failure) until after the 3rd try. 

java -cp /.../marklogic-corb-2.5.4.jar:/.../marklogic-xcc-11.0.0.jar: \
   -DXCC-PROTOCOL=xccs -DXCC-HOSTNAME=hostname -DXCC-PORT=8888 \
   -DXCC-USERNAME=user -DXCC-PASSWORD="*****" -DXCC-URL-ENCODE-COMPONENTS=always \
   -DMETRICS-LOG-LEVEL=debug -DTHREAD-COUNT=3 \
   -DURIS-MODULE=/.../uris.xqy'|ADHOC' -DPROCESS-MODULE=/.../process.xqy'|ADHOC' \
   -DSSL-KEYSTORE=/usr/home/cert.jks -DSSL-KEYSTORE-PASSWORD=***** \
   -DSSL-KEYSTORE-TYPE=JKS -DSSL-ENABLED-PROTOCOLS=TLSv1.2 -Djavax.net.debug=all \
   com.marklogic.developer.corb.Manager

**Comment by mlzarathustra** [comment]
OK, there IS a workaround, but it is ugly.  

I have to say: -DSSL-CONFIG-CLASS=com.marklogic.developer.corb.TwoWaySSLConfig

Which is anything but obvious.  

Thing is, if I'm specifying a keystore, it will never work unless I'm using this class, instead of the "trust anyone" class which does not pass KeyManagers to sslConfig.init(). So if I'm giving the application a keystore and a password for it, it should AUTOMATICALLY pick the correct class instead of stalling out with a mysterious message.

**Comment by hansenmc** [comment]
I agree, that it would be more convenient if CoRB automatically applied the TwoWaySSLConfig class if options specific to that implementation are applied to the job (and the user has not explicitly set **SSL-CONFIG-CLASS**). 

Similar to https://github.com/marklogic-community/corb2/issues/130 we can look to make configuration easier, and not have to explicitly set every single option.

**Comment by mlzarathustra** [comment]
I have a simple patch for this that I'll send along once the company whose network it's on decides it's OK for me to upload it, which hopefully they will. It was automatically blocked for containing source code.  It's just a simple check whether the keystore file is defined, and if so, it selects the "TwoWay" class. Which incidentally is NOT two-way, as it does not check the server certificate.

IMO that part of the application is way over-engineered, but I am not sure it's worth refactoring because of the need for testing.
