### ISSUE TITLE
Suggestion: add deprecated bind libraries to build.gradle

### ISSUE THREAD

**Issue by mlzarathustra** [marklogic-community/corb2#203]
It looks like the build was meant for javac version 8, which I can't easily install on this Mac (since the versions I've found insist on installing it globally, which I don't want to do).

I was able to get it to build with Java 18 by adding the following to build.gradle:
dependencies { ...

    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'com.sun.xml.bind:jaxb-core:2.3.0.1'
    implementation 'com.sun.xml.bind:jaxb-impl:2.3.7'
}

I suggest adding these to the official version.

**Comment by hansenmc** [comment]
https://github.com/marklogic-community/corb2/pull/214
