### ISSUE TITLE
Support bulk load/ingestion of xml files or acrhive files

### ISSUE THREAD

**Issue by bbandlamudi** [marklogic-community/corb2#22]
This is the first step towards supporting data ingestion through corb. Should have an option to specify permissions and collections.

**Comment by tvnpraveen** [comment]
Currently XQSync can load data into MarkLogic only if the input files are Zip files containing XML files. MLCP supports loading individual XML files in a folder but it is a much heavier tool to use. Also there is host name dependency unlike CoRB tool. 

Example if you are connecting to a host via IP as the connection, if it is a single host MLCP works fine but if it is a cluster it requires the hostnames and ips mapped in the environment you are running MLCP.

Having the bulk ingestion feature of XML files from a folder or an archive will help.
