### ISSUE TITLE
Provide ability to log metrics associated with query executions to ErrorLog

### ISSUE THREAD

**Issue by davidbcollins** [marklogic-community/corb2#39]
Metrics (e.g. total execution time) for the selector and transform could be written to the ErrorLog.  These could be implemented as trace events. Having this capability built in to the corb is desirable primarily from an operations standpoint:
1) ability to monitor which jobs are running when
2) visibility into how metrics associated with those jobs have changed over time (e.g. are the jobs speeding up after a change/upgrade to the infrastructure)

**Comment by bbandlamudi** [comment]
Thanks David! We will try to start working on it this quarter as there is a more immediate need for this feature compared to few other improvements we have in the pipeline.
