### ISSUE TITLE
Corb2 needs to print underlying exception when disk queue write fails. 

### ISSUE THREAD

**Issue by bbandlamudi** [marklogic-community/corb2#47]
We had a production job failue today with the exception "SEVERE: Error writing to DiskQueue backing store". DiskQueue.offer() method isn't printing the underlying exception, so we had no idea what went wrong. 

We need to examine similar instances in the code and try to print underlying exception or at least provide some information about what went wrong.

**Comment by hansenmc** [comment]
I believe that this is already resolved in the current development branch.

That message is printed if there is an IOException in the [DiskQueue.offer()](https://github.com/marklogic/corb2/blob/master/src/main/java/com/marklogic/developer/corb/DiskQueue.java#L189). The currently released version of that method does not include the exception object as a parameter of the `Logger.log()`, but in the development branch it does:
https://github.com/marklogic/corb2/blob/development/src/main/java/com/marklogic/developer/corb/DiskQueue.java#L189

**Comment by bbandlamudi** [comment]
Thanks Mads! I didn't realize that it was address already. For now, I suggested Ops team to use a different directory to write disk queue file as I thought it probably ran out of space, though I couldn't be certain with out underlying exception.
