### ISSUE TITLE
Provide real-time metrics for the Job as it progresses.

### ISSUE THREAD

**Issue by vjsaradhi** [marklogic-community/corb2#57]
It would be useful to have a mechanism for clients to fetch metrics on-demand for the job that is running.  Ex: Clients can connect to a http port that is opened as part of the corb job and continuously provide updates.

**Comment by hansenmc** [comment]
<img width="1301" alt="screen shot 2017-11-14 at 8 37 53 pm" src="https://user-images.githubusercontent.com/2940775/32816731-4613486e-c988-11e7-9712-7783cae17245.png">
<img width="966" alt="screen shot 2017-11-14 at 8 37 26 pm" src="https://user-images.githubusercontent.com/2940775/32816715-3526d372-c988-11e7-9aa5-ef81cdd9e7a1.png">
