### ISSUE TITLE
RFC: Change underlying implementation to use Data Movement SDK

### ISSUE THREAD

**Issue by jmakeig** [marklogic-community/corb2#61]
corb was one of the inspirations for the Data Movement SDK in the 4.x version of the Java Client API. How can we better align in terms of capabilities and to take advantage of each others’ work? For example, rather than corb implementing its own support for multi-host communication or host failover, would it be possible for it to use the built-in capability in DMSDK? Rather than the Java Client API building a CLI could we leverage/evolve corb to be that?

**Comment by hansenmc** [comment]
@damonfeldman had also asked about this recently. 

CORB uses XCC and has it's own batch/queue mechanism. It is possible to configure a CORB job to use custom implementation classes for things such as the PROCESS-TASK, but might need a custom class to execute the URIS-MODULE (and pre/post batch tasks) via DMSDK and might even need a custom Manager class, or at least expose additional config options to customize the thread pool and queue implementation. 

We can look to see if there is anything we can do to make it easier to plug in different implementations. However, it might wind up being easier creating a different app that depends on CORB and DMSD, extends/implements CORB classes, supports (the applicable) CORB options and additional options that would make sense for a DMSDK tool, and uses the Java client/DMSDK to communicate with MarkLogic.
