### ISSUE TITLE
warning message in CORB: -XX:+UseConcMarkSweepGC

### ISSUE THREAD

**Issue by GolaganiMohan** [marklogic-community/corb2#68]
Any help in resolving the warning message in the CORB job would be much appreciated.

WARNING: Slow receive! Consider increasing max heap size and using -XX:+UseConcMarkSweepGC
Jul 28, 2017 11:09:45 AM com.marklogic.developer.corb.Manager populateQueue
INFO: free memory: 999 MiB

**Comment by bbandlamudi** [comment]
In most cases you can try increasing the java max heap -Xmx value to resolve the issue. Occasionally, the box itself has a problem allocating memory or corb is slow to retrieve the data from ML. 

Also, could you post these questions to corb2@developer.marklogic.com (subscribe to mailing list http://developer.marklogic.com/mailman/listinfo/corb2) as this is not really a defect in corb.

**Comment by hansenmc** [comment]
The slow receive messages will be logged every 25,000th URI processed if it has taken more than 4 seconds. We might look to adjust that warning message, or change the thresholds.

https://github.com/marklogic-community/corb2/blob/824c9dfaee885105b703e01b6711fdd19b585bbd/src/main/java/com/marklogic/developer/corb/Manager.java#L757 

If the "free memory" message is at the INFO level, treat it as informational. It will log as a WARNING if your free memory is under 20%.  So, unless you see a WARNING reporting your memory, you are probably fine regardless of how fast your CORB job is processing records.

**Comment by hansenmc** [comment]
We have made adjustments in the 2.4.0 release to prevent these (confusing) log messages from occurring while processing the URIs and will only log when memory appears to be low. 
https://github.com/marklogic-community/corb2/blob/master/src/main/java/com/marklogic/developer/corb/Manager.java#L914

The slow receive log message will still be produced when reading the URIs from the URIS module.
