### ISSUE TITLE
Error: Could not find or load main class com.marklogic.developer.corb.Manager

### ISSUE THREAD

**Issue by sreehesh** [marklogic-community/corb2#69]
I am new to CORB and was trying a sample code. After building the CORB, I gave the following command to check if it a able to locate the main class in the path, but it gives the below error..
command: 
java -server -cp .:marklogic-xcc-9.0.2.jar:marklogic-corb-2.3.2.jar
        com.marklogic.developer.corb.Manager

Error: 
         Error: Could not find or load main class com.marklogic.developer.corb.Manager.

I followed below steps for building the CORB
--------------------------------------------------------
1. download and copy(unzipped) the "corb2-master.zip" to my local machine folder C:\Sreehesh\ML\CORB\
2. in the command prompt run script ./gradlew build
3. Download and copy(unzip) "MarkXCC.Java-9.0.2.zip to the same local folder.

**Comment by hansenmc** [comment]
The commandline examples assume a Linux environment. For windows, the path separator is ';' instead of ':'. Try changing to use:

    java -server -cp .;marklogic-xcc-9.0.2.jar;marklogic-corb-2.3.2.jar com.marklogic.developer.corb.Manager

**Comment by sreehesh** [comment]
I changed from : to ; and it worked..thank you for your quick response.
