### ISSUE TITLE
Provide an option to hide the URI to be printed to log or console

### ISSUE THREAD

**Issue by bbandlamudi** [marklogic-community/corb2#71]
In certain use cases URI can contain identification information and should not be printed to console out or log file. This makes it difficult for operations to protect the log files or scrub them before sharing with others. Though this use case normally happens in case of URIS-FILE, it can potentially be useful even for query loader. 

If the parameter (name??) is specified, we should avoid logging the URI when a milestone is reached during loading or processing, while handling exceptions or any other cases where we print the URIs to console.

**Comment by hansenmc** [comment]
Suggest that we use "**URIS-**" prefix for the property, to group it with the other URIS related properties (**URIS-MODULES, URIS-FILE, URIS-LOADER, URIS-REPLACE-PATTERN**).

What about calling it **URIS-SENSITIVE**?

**Comment by bbandlamudi** [comment]
Yes, it is definitely a good idea to use the URIS- prefix for this property. However, I am not completely sold on the name URIS-SENSITIVE as it is not really intuitive for what this property is trying to achieve. How about something more obvious like URIS-HIDDEN or URIS-REDACTED etc.

**Comment by hansenmc** [comment]
Of those two, I like URIS-REDACTED better.

**Comment by bbandlamudi** [comment]
URIS-REDACTED it is :) 
@hansenmc - Could you take this enhancement? It is probably not a high priority as folks have been living with it for a while.
