### ISSUE TITLE
Fatal error: java.lang.OutOgMemoryError: Java heap space

### ISSUE THREAD

**Issue by sreehesh** [marklogic-community/corb2#78]
I am getting the below error while throwing the documents in to a flat file using Corb job. These are big documents, each document adds 0.15 MB to the flat file. I was able process upto 800 documents, resulting in 96MB file. When I tried to process 900 documents, it gave we below error.

Fatal error: java.lang.OutOfMemoryError: Java heap space

![image](https://user-images.githubusercontent.com/29737635/34087329-52e5ae86-e370-11e7-8978-96e5c2295a3c.png)

My requirement is to create report flat file for more than thousands of documents. Please help.

**Comment by sreehesh** [comment]
The issue got resolved when I reduced the Batch Size from 1000 to 100.

**Comment by hansenmc** [comment]
Also, how many threads were you running with? 

You will need to ensure that you have enough RAM to buffer the result from each process module execution as it is being written. If your documents are 0.15MB, estimated memory footprint would be 0.15 * BATCH-SIZE * THREAD-COUNT.

Try allocating more RAM, reducing the batch size, and/or the thread count (as you noted above) to stay within your available resources.
