### ISSUE TITLE
NullPointerException when export file is specified from local directory (with out parent)

### ISSUE THREAD

**Issue by bbandlamudi** [marklogic-community/corb2#85]
Need to check if the parent file exists before trying to create folders. 

Caused by: java.lang.NullPointerException
	at com.marklogic.developer.corb.ExportToFileTask.writeToFile(ExportToFileTask.java:54)
	at com.marklogic.developer.corb.ExportToFileTask.processResult(ExportToFileTask.java:105)
	at com.marklogic.developer.corb.AbstractTask.invokeModule(AbstractTask.java:19

**Comment by hansenmc** [comment]
Jumping up to the `getParentFile()` may not be necessary. We might be able to just do `exportFile.mkdirs();`?

What was the scenario that this happened in which a file didn't have a parent? Was it an output file at the root of the drive? i.e. `/myOutput.txt`?

**Comment by bbandlamudi** [comment]
Hi Mads,
I just specified the
EXPORT-FILE-NAME=myfile.txt
expecting the file to be created in current directory where the script was running from in 2.4.1 (this was what I do usually). No export file folder. Finally I ended up using export file name as “output/myfile.txt” and it worked.

Yes, jumping to parent directory might not be required - we can test it.

Note: I was testing/using the new feature to stream individual source files from a local zip file and write a simple transform to insert them to a modules database. This works great, but I could have used an example (for each use case with loaders) text and use Cade. Needed to figure out by looking at source code and errors. I am now tempted to cleanup/make generic a transform that takes optional base directory (defaults to /), permissions (defaults to user default perm) and collections (defaults to no perm) as input and bundle with corb or at least provide a downloadable file. This can be used as a flash deploy tool for source modules. Or developers can modify as needed.

Thanks,
Bhagat

On Jun 12, 2018, at 10:43 PM, Mads Hansen <notifications@github.com<mailto:notifications@github.com>> wrote:


Jumping up to the getParentFile() may not be necessary. We might be able to just do exportFile.mkdirs();?

What was the scenario that this happened in which a file didn't have a parent? Was it an output file at the root of the drive? i.e. /myOutput.txt?

**Comment by hansenmc** [comment]
okay, now I see. If only the filename is provided for the EXPORT-FILE-NAME, and the exportDir is `null`, then the File object created in the [ExportToFileTask.getExportFile()](https://github.com/marklogic-community/corb2/blob/master/src/main/java/com/marklogic/developer/corb/ExportToFileTask.java#L99) has a null parent.

It looks like we could adjust the two places where we are attempting to create these directories to first resolve the absolute file:

    exportFile.getAbsoluteFile().getParentFile().mkdirs();

We would want to adjust both the [writeToFile()](https://github.com/marklogic-community/corb2/blob/master/src/main/java/com/marklogic/developer/corb/ExportToFileTask.java#L54) and [writeToExportFile() ](https://github.com/marklogic-community/corb2/blob/master/src/main/java/com/marklogic/developer/corb/ExportToFileTask.java#L69)methods, or maybe push this down into the [getExportFile()](https://github.com/marklogic-community/corb2/blob/master/src/main/java/com/marklogic/developer/corb/ExportToFileTask.java#L89) method that they both are invoking and have it invoke `mkdirs()` prior to returning the File?
