### ISSUE TITLE
FileDirectoryUrisLoader needs to remove the loader path from the file path in metadata

### ISSUE THREAD

**Issue by bbandlamudi** [marklogic-community/corb2#86]
If the loader path is `/path/to/filesroot/` and there is a directory structure under the loader path ex: `/path/to/loader/lib/mylib.xqy` and `/path/to/loader/services/transform/mymodule.xqy`, the file path in the metadata needs include only `lib/mylib.xqy` and `services/transform/mymodule.xqy`. 

We can include the loader path as a separate metadata item for the context i.e., similar to how we include zip file name for zip uris loader.

**Comment by hansenmc** [comment]
I'll change so that if **LOADER-PATH** is specified, then that directory will be set as the **source** metadata property(similar to what is done for the Zip filename in the FileUrisZipLoader) and if the file **path** value starts with the **LOADER-PATH** then the substring after will be used.
