### ISSUE TITLE
Recommended BATCH-SIZE

### ISSUE THREAD

**Issue by navdeepsekhon** [marklogic-community/corb2#87]
Not really an issue.

What is the recommended `BATCH-SIZE` for jobs with update queries? Any guidelines?

**Comment by bbandlamudi** [comment]
Recommend batch size is 1 for updates as we typically don’t want multiple updates to be part of same transaction and don’t want very large transactions. Please note each invocation is a single transaction unless you do an eval inside your query.

Having said, we sometimes use batch size more than 1  for smaller updates and require better performance.

Thanks,
Bhagat

On Aug 15, 2018, at 10:35 AM, Navdeep Sekhon <notifications@github.com<mailto:notifications@github.com>> wrote:


Not really an issue.

What is the recommended BATCH-SIZE for jobs with update queries? Any guidelines?
