### ISSUE TITLE
Indicate which XCC connection options are missing when failing to init ConnectionSourcePool

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/corb2#91]
Hi, 

This in `AbstractManager.java` is wrong of course:

```
if (StringUtils.anyIsNull(uriAsStrings) && StringUtils.anyIsNull(username, password, hostnames, port)) {
            throw new CorbException(String.format("Either %1$s or %2$s, %3$s, %4$s, and %5$s must be specified",
                    XCC_CONNECTION_URI, XCC_USERNAME, XCC_PASSWORD, XCC_HOSTNAME, XCC_PORT));
        }
```

This should be URI is NULL **OR** any separate options is null. 

@bbandlamudi

**Comment by bbandlamudi** [comment]
Interesting. Thanks for looking. We will need to address this. I am more worried about potential impact.

Bhagat

On Mar 7, 2019, at 12:56 AM, Jos van Roosmalen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

This in AbstractManager.java is wrong of course:

if (StringUtils.anyIsNull(uriAsStrings) && StringUtils.anyIsNull(username, password, hostnames, port)) {
            throw new CorbException(String.format("Either %1$s or %2$s, %3$s, %4$s, and %5$s must be specified",
                    XCC_CONNECTION_URI, XCC_USERNAME, XCC_PASSWORD, XCC_HOSTNAME, XCC_PORT));
        }


This should be URI is NULL OR any separate options is null.

@bbandlamudi<https://github.com/bbandlamudi>

**Comment by bbandlamudi** [comment]
I take my previous comment back - It is only an error if BOTH cases are true - 1. full XCC URI is not specified  2. XCC URI cannot be constructed from the parts. If either of these two are specified, Corb can user or construct XCC URI to talk to ML, so not an error.

**Comment by josvanroosmalen** [comment]
Now I reread, I agree with you, however then I would like to see WHICH option is EMPTY. Now it is a wild guess.

**Comment by bbandlamudi** [comment]
Yeah, I wish it could have been a bit more clear. I agree that it has generally not been a problem since corb is traditionally run as a stand alone job and easy to spot mis configuration, so thats probably by no one complained it until now. May be we could address this in future.

**Comment by hansenmc** [comment]
What if we added something like this, to log a WARNING message indicating which of the XCC connection parameters are null when the minimum requirements are not set:

```
        if (StringUtils.anyIsNull(uriAsStrings) && StringUtils.anyIsNull(username, password, hostnames, port)) {
            String[] connectionParameters = {XCC_CONNECTION_URI, XCC_USERNAME, XCC_PASSWORD, XCC_HOSTNAME, XCC_PORT};
            for (String connectionParameter : connectionParameters) {
               if (StringUtils.anyIsNull(getOption(connectionParameter))) {
                   LOG.warning(MessageFormat.format("{0} is null", connectionParameter));
               }
            }
            throw new CorbException(String.format("Either %1$s or %2$s, %3$s, %4$s, and %5$s must be specified",
                    XCC_CONNECTION_URI, XCC_USERNAME, XCC_PASSWORD, XCC_HOSTNAME, XCC_PORT));
        }

```

It would generate messages like this:

> Mar 08, 2019 8:59:25 AM com.marklogic.developer.corb.AbstractManager initContentSourcePool
> WARNING: XCC-CONNECTION-URI is null
> Mar 08, 2019 8:59:27 AM com.marklogic.developer.corb.AbstractManager initContentSourcePool
> WARNING: XCC-USERNAME is null
> Mar 08, 2019 8:59:28 AM com.marklogic.developer.corb.AbstractManager initContentSourcePool
> WARNING: XCC-PASSWORD is null
> Mar 08, 2019 8:59:29 AM com.marklogic.developer.corb.AbstractManager initContentSourcePool
> WARNING: XCC-HOSTNAME is null
> Mar 08, 2019 8:59:30 AM com.marklogic.developer.corb.AbstractManager initContentSourcePool
> WARNING: XCC-PORT is null

If that sounds reasonable, we can also look to see where else we test for minimum XCC connection properties, to see if it would be useful to move that into a convenience method and use in other places.

**Comment by bbandlamudi** [comment]
Yes - but we will still need avoid unnecessary warnings as developers (especially operations) will be alarmed. Users will only specify connection uri or individual parts and not both.

**Comment by hansenmc** [comment]
Right, these warnings would only be generated if the minimum required XCC connection options are missing (either no XCC-CONNECTION-URI OR the individual values are not all specified). So, you would only get the warnings when it throws the exception. i.e. it wouldn't be logging a warning that the XCC-PORT is null if the XCC-CONNECTION-URI is specified
