### ISSUE TITLE
Unable to execute CORB from Java code

### ISSUE THREAD

**Issue by dbarriguete** [marklogic-community/corb2#94]
I have a Java application and I'm trying to execute CORB from my code.

I added connection string: 
```
Properties systemProperties = System.getProperties();		                     
systemProperties.setProperty("-DXCC-CONNECTION-URI", "xcc://admin:currentpassword@localhost:9071");
systemProperties.setProperty("XCC_CONNECTION_URI", "xcc://admin:currentpassword@localhost:9071");
systemProperties.setProperty("XCC-CONNECTION-URI", "xcc://admin:currentpassword@localhost:9071");
systemProperties.setProperty("URIS-MODULE","/corb/" + this.Name + "/uris.xqy");
systemProperties.setProperty("URIS-MODULE.package-id", this.Package_ID);
systemProperties.setProperty("URIS-MODULE.import-type", this.ImportType);

String[] args = new String[1];

args[0] = "local";
//it executes de Corb manager
com.marklogic.developer.corb.Manager.main(args); // it always fails here
```
        
But I always receive an error about missing XCC-CONNECTION-URI:

com.marklogic.developer.corb.AbstractContentSourcePool createContentSource
GRAVE: Problem creating content source. Check if URI is valid. If encrypted, check if options are configured correctly for host null:-1local

do you know if I'm misspelling property for XCC-CONNECTION-URI ?

Thanks in advance guys

**Comment by dbarriguete** [comment]
After several testing with previous code I found that the arguments array sent to main method are configuring the execution variables, so that the way to send connection string is: 

(Brand new code)
```
String[] args = new String[1];
args[0]="xcc://admin:currentpassword@localhost:9071";

//it executes de Corb manager
com.marklogic.developer.corb.Manager.main(args);
```
With this code now I receive the following error: 
may 29, 2019 12:47:28 PM com.marklogic.developer.corb.Manager main
GRAVE: Error while running CORB
com.marklogic.developer.corb.CorbException: While invoking URIS-MODULE

My question is: Where may I see the order of how I should send arguments? and what may I do if any argument is null or empty?


Thanks in advance guys

**Comment by hansenmc** [comment]
The commandline args are:
1. XCC-CONNECTION-URI
2. COLLECTION-NAME 
3. PROCESS-MODULE  
4. THREAD-COUNT 
5. URIS-MODULE 
6. MODULE-ROOT
7. MODULES-DATABASE
8. INSTALL
9. PROCESS-TASK
10. PRE-BATCH-MODULE
11. PRE-BATCH-TASK
12. POST-PROCESS-MODULE
13. POST-BATCH-TASK
14. EXPORT-FILE-DIR
15. EXPORT-FILE-NAME
16. URIS-FILE

They are listed in the README.md in the [Usage 1 - commandline options](https://github.com/marklogic-community/corb2#usage-1---command-line-options) example.

Use an empty string `""` for an argument that is null or empty. Take a look at some of the tests for examples: https://github.com/marklogic-community/corb2/blob/master/src/test/java/com/marklogic/developer/corb/ManagerIT.java#L140

Your original issue was that you were setting the system property incorrectly. When setting the system property pragmatically, you just specify the property name (i.e. `systemProperties.setProperty("XCC-CONNECTION-URI", "xcc://admin:currentpassword@localhost:9071");`). You only use `-D` prefix when setting system properties on the commandline.

If you are going to be invoking CORB programatically, then you may find it easier to specify the options via Java Properties object and to use the static Options properties to reference the keys:

    Properties properties = new Properties();
    properties.setProperty(Options.XCC_CONNECTION_URI, "xcc://admin:currentpassword@localhost:9071");
    properties.setProperty(Options.URIS_MODULE, "/corb/" + this.Name + "/uris.xqy");
    properties.setProperty(Options.URIS_MODULE + ".package-id", this.Package_ID);
    properties.setProperty(Options.URIS_MODULE + ".import-type", this.ImportType);
    Manager manager = new Manager();
    manager.init(properties);
    manager.run()

**Comment by dbarriguete** [comment]
Hi Hansenmc, thanks for your answer.

Additionally I had wrong my args object value because it should go as null or empty, so that the configuration would be taken from system properties, if args[] has at least 1 element non empty string then configuration is being taken exclusively from args[] 

My new code: 

            ```
    //it configures all the system properties with their respective values.
		Properties systemProperties = System.getProperties();
		
		systemProperties.setProperty("XCC-CONNECTION-URI", "xcc://admin:crrentpassword@localhost:9071");
		systemProperties.setProperty("URIS-MODULE","/corb/" + this.Name + "/uris.xqy");
		systemProperties.setProperty("URIS-MODULE.package-id", this.Package_ID);
		systemProperties.setProperty("URIS-MODULE.import-type", this.ImportType
		systemProperties.setProperty("BATCH-SIZE", ""+this.BatchSize);
		systemProperties.setProperty("THREAD-COUNT","8");
		systemProperties.setProperty("MODULE-ROOT","/");
		systemProperties.setProperty("METRICS-COLLECTIONS", this.Package_ID + "_" + this.Name); // # we are using this flag to pass the package id and the corb name into save-metrics module
		systemProperties.setProperty("METRICS-NUM-SLOW-TRANSACTIONS","2");
		systemProperties.setProperty("METRICS-NUM-FAILED-TRANSACTIONS","10");
		systemProperties.setProperty("METRICS-ROOT","/prisma/metrics/");
		systemProperties.setProperty("METRICS-LOG-LEVEL","error");
		systemProperties.setProperty("METRICS-DATABASE","Documents"); // # we are storing metrics as log events. The database just has to be set here, otherwise the save-metrics module is not executed.
		systemProperties.setProperty("METRICS-MODULE","/corb/save-metrics.xqy
 com.marklogic.developer.corb.Manager.main(null);

```


Now I'm reviewing values of my variables and hope getting a correct execution soon.
