### ISSUE TITLE
 New Feature request to capture metadata node from input xml and send it to transform along with xpath node

### ISSUE THREAD

**Issue by lsaishanker** [marklogic-community/corb2#95]
Hi,
We have an input xml which has a metadata node along with multiple child nodes of root element. Currently CORB 2.4.4 using the FileUrisStreamingXMLLoader captures each child node from the input xml (based on xpath/default processing) and sends it to the transform. It will be nice if we can capture a metadata node along with the child node and send it to the transform.
Thank you.

**Comment by hansenmc** [comment]
So, you are interesting in identifying a node (or sequence of nodes) in the input document that you would want sent with each of the selected child nodes that are sent to the transform/process module.

We would need an additional option to specify the XPath to select the metadata node(s).

For the DOM processor, it should be pretty straightforward.

For the streaming parser, we would need to see whether it makes sense to perform 1 pass to select the metadata (if the option to select is specified), and then a second pass to select the content for processing. That would ensure the metadata is captured and sent with all content nodes, even if it happened to be at the end of the doc as one of the last nodes.

**Comment by bbandlamudi** [comment]
This is what I am thinking.. 
1. Add an additional option XML-METADATA that takes the path to metadata node. 
2. Read the metadata into a local variable as part of extractElement method and later push it to properties to PRE-BATCH-MODULE custom input variable (lets call it 'metadata'?). Also, if envelope is enabled for PROCESS_MODULE, add this metadata xml into the envelope as well
3. There can be more than one metadata elements (i.e., instead of all the metadata under a single parent element structure). So, should we accept a comma separated xpaths? This can quickly become tricky to manage. We can sleep on it for a bit and think it over.

**Comment by bbandlamudi** [comment]
Pushed all my changes to **xmlmetadata** git branch. I have added enough test cases to cover the metadata use cases. I am planning to update the large file integration test to include metadata soon. I have tested several use cases locally and may plan to test a large file @lsaishanker sent me as well with added metadata. Its probably good for the release, but I will hold off for a bit until I ran through all my tests. 

Note: integration tests are failing on FileDirectoryUrisLoader and FileZipUrisLoader around the temp directory/file and throwing (export) file not found exceptions. Not sure what is going on @hansenmc  - Is this something you could help me with?

**Comment by hansenmc** [comment]
I’ll take a look at the integration tests. It is possible that there is a hard coded path somewhere. Are you running on a Mac or Windows?

**Comment by bbandlamudi** [comment]
its probably environment related - I am running on Mac OS.

**Comment by hansenmc** [comment]
All of the integration tests pass for me. Curious what the errors were. I'd like for them to run for everyone. 

I just pushed some minor changes to this branch with some minor refactoring (same functionality, just splitting out logic into functions and consolidating)

**Comment by bbandlamudi** [comment]
@hansenmc  - Pushed all the changes to xmlmetadata branch and cerated a pull request for you. 
I added additional integration test with sample code that can be used as a starting point to loading complex xml files into marklogic that uses all the hooks.
