### ISSUE TITLE
Error running CORB with Password containing Special Characters

### ISSUE THREAD

**Issue by Zipunrar** [marklogic-community/corb2#99]
Hi,

we are using the CORB Framework to run XQuery Scripts on our MarkLogic server (as designed to do so). However we are currently running into an error because a member of my team uses a password for the server that contains a "%" at the end.

Example of an equivalent password: abcde0=(%

The password will be extracted from a properties file.
Running CORB with the appropriate parameters like:

  java -cp "corb/marklogic-corb-2.3.1.jar;xcc/marklogic-xcc-8.0.5.jar" -DOPTIONS-FILE=test.properties com.marklogic.developer.corb.Manager

However this call fails with the error:

  java.net.URISyntaxException: Malformed escape pair at index 18: xcc://sampleUser:abcde0=(%@1.2.3.4:1234/datahub-content

Searching in the source of CORB Framework, I found the class "StringUtils" that does encode the parameters if they are not already encoded. However because the password will be checked by
decoding it and that fails it is not possible to execute CORB at all.

I think a better solution here would be to allow special characters in the password as in my example by catching the exception and handle this case as "parameter is not encoded".
This would ignore the case that the encoding is invalid however could be solved by logging
a warning that it may be that the login fails or something.

What do you think about?

**Comment by hansenmc** [comment]
From what you posted, it appears that you are running CORB v2.3.1. 

Changes were made in the v2.4.0 release to URLEncode username/password values https://github.com/marklogic-community/corb2/issues/36 

Try upgrading to the latest latest CORB version 2.4.5.

You could also URLEncode the values yourself.

**Comment by Zipunrar** [comment]
Thanks for the fast response!

I don't think that a version upgrade will help here since I am aware that I am using an older version. However to analyze the problem I was using the current code base from github at master branch.

Sure I could encode the password myself, however this would not very userfriendly, right?

So my suggestion would be handle the exception thrown by the decoder during the check in order to
catch the 90% of all cases where the users are not encoding the password and the others how do.
The small part less having a wrong encoding will just get a warning in the log. That should do it.

Another solution would be to just encode everytime assuming and documenting that the credentials within the properties or parameters should not be encoded at all (which will be true for most people).
But that is just my opinion.

We will checkout the new version of CORB and try it. Reporting back as soon as we have results that way.

**Comment by bbandlamudi** [comment]
You are not actually changing the passwords. Simply replacing the problem character with encoding (you can google for encoding reference).

Thanks,
Bhagat




On Jul 1, 2019, at 9:02 AM, Zipunrar <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the fast response!

I don't think that a version upgrade will help here since I am aware that I am using an older version. However to analyze the problem I was using the current code base from github at master branch.

Sure I could encode the password myself, however this would not very userfriendly, right?

So my suggestion would be handle the exception thrown by the decoder during the check in order to
catch the 90% of all cases where the users are not encoding the password and the others how do.
The small part less having a wrong encoding will just get a warning in the log. That should do it.

Another solution would be to just encode everytime assuming and documenting that the credentials within the properties or parameters should not be encoded at all (which will be true for most people).
But that is just my opinion.

We will checkout the new version of CORB and try it. Reporting back as soon as we have results that way.

**Comment by Zipunrar** [comment]
So we test it with the current version as suggested but no luke, same error:

`Error initializing CORB URLDecoder: Incomplete trailing escape (%) pattern
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
 at java.net.URLDecoder.decode(URLDecoder.java:187)
 at com.marklogic.developer.corb.util.StringUtils.urlDecode(StringUtils.java:385)
 at com.marklogic.developer.corb.util.StringUtils.isUrlEncoded(StringUtils.java:362)
 at com.marklogic.developer.corb.util.StringUtils.urlEncodeIfNecessary(StringUtils.java:352)
 at com.marklogic.developer.corb.util.StringUtils.getXccUri(StringUtils.java:334)
 at com.marklogic.developer.corb.AbstractManager.initContentSourcePool(AbstractManager.java:277)
 at com.marklogic.developer.corb.AbstractManager.init(AbstractManager.java:192)
 at com.marklogic.developer.corb.Manager.init(Manager.java:172)
 at com.marklogic.developer.corb.AbstractManager.init(AbstractManager.java:168)
 at com.marklogic.developer.corb.Manager.main(Manager.java:129)`

In order to resolve we must encode the password on our side before adding it to the properties file or the parameters.

**Comment by Zipunrar** [comment]
For all others that may stumble across this issue. We do have enhanced our gradle task with
explicit encoding upfront before executing CORB.

`task runCORB {
	group = 'MarkLogic'
	description = 'Runs CORB for simple bulk operations on a MarkLogic server.'

	doLast {
		println 'Running CORB on ' + markLogicServer
		exec {
			args = ['-cp', corbExecutable + File.pathSeparator + xccLibrary,
					'-DOPTIONS-FILE=' + configDir + "$optFile",
                    '-DXCC-USERNAME=' + URLEncoder.encode(username, StandardCharsets.UTF_8.name()) +
                    '-DXCC-PASSWORD=' + URLEncoder.encode(password, StandardCharsets.UTF_8.name()) +
					'com.marklogic.developer.corb.Manager']

			executable = 'java'
		}
	}
}`

See [CORB Documentation - Usage](https://github.com/marklogic-community/corb2#usage-4---combination-of-properties-file-with-java-system-properties-and-command-line-options) for details.

In some way this is much saver for all our team members to use and makes sense for security reasons because the password and the username does not reside within the configuration file itself.

Anyway thanks for the help.
